-- Generated by scripts/hypr2lua.
-- Source: omarchy-florida-man-theme/hyprland.conf

local activeBorderGradient = {
  colors = { "rgba(e78284ff)", "rgba(ef9f76ff)", "rgba(e5c890ff)", "rgba(a6d189ff)", "rgba(81c8beff)", "rgba(99d1dbff)", "rgba(85c1dcff)", "rgba(8caaeeff)", "rgba(e78284ff)" },
  angle = 45,
}
local inactiveShadowColor = "rgba(000000aa)"
local activeShadowColor = "rgba(000000bb)"

hl.config({
  general = {
    col = {
      active_border = activeBorderGradient,
      inactive_border = inactiveBorderColor,
    },
    border_size = 6,
    gaps_in = 8,
    gaps_out = 12,
  },
  group = {
    col = {
      border_active = activeBorderGradient,
    },
  },
  decoration = {
    rounding = 12,
    rounding_power = 4,
    blur = {
      enabled = true,
      size = 4,
      passes = 2,
      noise = 0.16,
    },
    shadow = {
      enabled = true,
      range = 20,
      render_power = 6,
      offset = "2 2",
      color = activeShadowColor,
      color_inactive = inactiveShadowColor,
    },
  },
})

hl.curve("easeInOutQuant", { type = "bezier", points = { { 0.76, 0 }, { 0.24, 1 } } })
hl.curve("linear", { type = "bezier", points = { { 0, 0 }, { 1, 1 } } })

hl.animation({
  leaf = "border",
  enabled = true,
  speed = 20,
  bezier = "default",
})
hl.animation({
  leaf = "borderangle",
  enabled = true,
  speed = 55,
  bezier = "linear",
  style = "loop",
})

hl.window_rule({
  opacity = "1.0 override",
  match = {
    class = "^(brave-youtube\\\\.com__-Default)$",
  },
})
hl.window_rule({
  opacity = "1.0 override",
  match = {
    class = "^(chrome-youtube\\\\.com__-Default)$",
  },
})
